- hosts: rpi
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: install dotnet prerequisites
      apt:
        update_cache: yes
        state: present
        name:
          - libc6
          - libgcc1
          - libgssapi-krb5-2
          - libicu66
          - libssl1.1
          - libstdc++6
          - zlib1g
