- hosts: rpi
  become: yes
  become_user: root
  become_method: sudo
  tasks:
    - name: apt - update cache
      apt:
        update_cache: yes
    - name: apt - upgrade full
      apt:
        upgrade: full
    - name: apt - autoremove
      apt:
        autoremove: yes
    - name: apt - autoclean
      apt:
        autoclean: yes
